version: 2
sources:
  - name: EU
    schema: Eu_death
    tables:
      - name: Liver
        identifier: Chronic_liver_disease
      - name: THH
        identifier: Tuberculose_HIV_and_hepatitis
      - name: cancer
        identifier: cancer
      - name: Heart
        identifier: ischaemic_heart_diseases
      - name: Nervous
        identifier: nervous_system
      - name: Pneumonia
        identifier: pneumonia
      - name: Total
<<<<<<< HEAD
        identifier: total
=======
        identifier: total
>>>>>>> 8f3648c277e4befdbb9f4e25f6d6733ce919dc6a
