version: 2
sources:
  - name: EU
    schema: Eu_death
    tables:
      - name: Liver
        identifier: Chronic_liver_disease
        description: dataset on the nb of death in EU by chronic liver diseases 
        columns:
          - name: Country
            description: The EU Country
            tests:
              - unique
              - not_null 
          - name: Year
            description: The timeline of the analysis
            tests:
              - unique
              - not_null  
          - name: Value 
            description: The death rate 
            tests:
              - unique
              - not_null 
          - name: maladie
            description: the name of the diase 
            tests:
              - unique
              - not_null 
      - name: THH
        identifier: Tuberculose_HIV_and_hepatitis
        description: dataset on the nb of death in EU by Tubercoluse, HIV and Hepatitis 
        columns:
          - name: Country
            description: The EU Country
            tests:
              - unique
              - not_null 
          - name: Year
            description: The timeline of the analysis 
            tests:
              - unique
              - not_null 
          - name: Value 
            description: The death rate 
            tests:
              - unique
              - not_null 
          - name: maladie
            description: the name of the diase
            tests:
              - unique
              - not_null 
        
      - name: cancer
        identifier: cancer
        description: dataset on the nb of death in EU by cancer 
        columns:
          - name: Country
            description: The EU Country 
            tests:
              - unique
              - not_null
          - name: Year
            description: The timeline of the analysis 
            tests:
              - unique
              - not_null
          - name: Value 
            description: The death rate 
            tests:
              - unique
              - not_null
          - name: maladie
            description: the name of the diase
            tests:
              - unique
              - not_null
        
      - name: Heart
        identifier: ischaemic_heart_diseases
        description: dataset on the nb of death in EU by heart diases
        columns:
          - name: Country
            description: The EU Country 
            tests:
              - unique
              - not_null
          - name: Year
            description: The timeline of the analysis 
            tests:
              - unique
              - not_null
          - name: Value 
            description: The death rate 
            tests:
              - unique
              - not_null
          - name: maladie
            description: the name of the diase 
            tests:
              - unique
              - not_null
       
      - name: Nervous
        identifier: nervous_system
        description: dataset on the nb of death in EU by nervous system
        columns:
          - name: Country
            description: The EU Country 
            tests:
              - unique
              - not_null
          - name: Year
            description: The timeline of the analysis 
            tests:
              - unique
              - not_null
          - name: Value 
            description: The death rate 
            tests:
              - unique
              - not_null
          - name: maladie
            description: the name of the diase 
            tests:
              - unique
              - not_null
       
      - name: Pneumonia
        identifier: pneumonia
        description: dataset on the nb of death in EU by pneumonia
        columns:
          - name: Country
            description: The EU Country 
            tests:
              - unique
              - not_null
          - name: Year
            description: The timeline of the analysis
            tests:
              - unique
              - not_null 
          - name: Value 
            description: The death rate 
            tests:
              - unique
              - not_null
          - name: maladie
            description: the name of the diase
            tests:
              - unique
              - not_null 

      - name: Total
        identifier: total
        description: dataset on the nb of death in EU 
        columns:
          - name: Country
            description: The EU Country 
            tests:
              - unique
              - not_null
          - name: Year
            description: The timeline of the analysis
            tests:
              - unique
              - not_null 
          - name: Value 
            description: The death rate
            tests:
              - unique
              - not_null
          - name: maladie
            description: the name of the diase 
            tests:
              - unique
              - not_null

  - name: depense
    schema: depense_sante
    tables:
      - name: Ameli_depenses
        identifier: Ameli_depenses_pathologies_france_2015 _2022
        description: Jeu de données sur les dépenses de santé par pathologie en France de 2015 à 2022

  - name: depistage
    schema: Depistage_cancer_FR
    tables:
      - name: cancer_sein
        identifier: depistage_cancer_sein
        description: Jeu de données sur les données de dépistage pour le cancer du sein en France de 2005 à 2023

      - name: cancer_uterus
        identifier: depistage_cancer_uterus
        description: Jeu de données sur les données de dépistage pour le cancer de l'utérus en France de 2005 à 2020

